version: '3'

services:
    client:
        build: .
        container_name: client
        ports:
            - 3000:3000
        volumes:
            - ./client:/home/node/app
    server:
        build: .
        container_name: server
        ports:
            - 5000:5000
        volumes:
            - ./server:/home/node/app
    postgres:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        environment:
            POSTGRES_PASSWORD: example
